[package]
name = "scrutinise"
version = "0.0.0"
edition = "2021"
authors = ["Loky HARK"]
description = "Nuclear Kernel Library"
license = "MIT"
repository = "https://github.com/nkl-org/scrutinise"
keywords = ["nuclear"]
categories = ["science"]
